### ISSUE TITLE
格式有问题

### ISSUE THREAD

**Issue by YoungKang1222** [datawhalechina/Daily-interview#1]
举个例子：
![image](https://user-images.githubusercontent.com/30460985/58446344-fe852f80-8132-11e9-9a70-b3a70b4441bf.png)

**Comment by xiaorancs** [comment]
你好，谢谢提出问题，我们之后会给出相应的解决方案。目前，你可以先clone到本地，用相关md编辑器打开，应该就会回复正常。

**Comment by xiaorancs** [comment]
@YoungKang1222 

你好，谢谢提出问题，我们之后会给出相应的解决方案。
目前，你可以先clone到本地，用相关md编辑器打开，应该就会回复正常。

**Comment by YoungKang1222** [comment]
> @YoungKang1222
> 
> 你好，谢谢提出问题，我们之后会给出相应的解决方案。
> 目前，你可以先clone到本地，用相关md编辑器打开，应该就会回复正常。

好的 谢谢

**Comment by YoungKang1222** [comment]
您好 尝试了多种md编辑器后，还是同样的问题

**Comment by xiaorancs** [comment]
> 您好 尝试了多种md编辑器后，还是同样的问题

你好，VSCode使用插件应该可以解决问题。如果还有问题，请联系我，xiaoranone@126.com

**Comment by YoungKang1222** [comment]
您好，插件叫什么名字




| |
杨康
|
|
邮箱：18375320027@163.com
|

签名由 网易邮箱大师 定制

在2019年06月20日 20:34，xiaoran 写道：

您好 尝试了多种md编辑器后，还是同样的问题

你好，VSCode使用插件应该可以解决问题。如果还有问题，请联系我，xiaoranone@126.com

**Comment by xiaorancs** [comment]
> 您好，插件叫什么名字 | | 杨康 | | 邮箱：18375320027@163.com | 签名由 网易邮箱大师 定制 在2019年06月20日 20:34，xiaoran 写道： 您好 尝试了多种md编辑器后，还是同样的问题 你好，VSCode使用插件应该可以解决问题。如果还有问题，请联系我，xiaoranone@126.com — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or mute the thread.

Markdown All in One
