### ISSUE TITLE
转载问题

### ISSUE THREAD

**Issue by Mic-JasonTang** [datawhalechina/Daily-interview#2]
可将您的内容放到我博客吗？
会注明来源。

**Comment by xiaorancs** [comment]
没有及时回复，实在不好意思，你可以放到博客上，但请注明转载出处。Datawhale是一个非盈利的 开源学习组织，致力于构建一个纯粹的学习圈子，帮助学习者更好地成长。我们专注于机器学习，深度学习，编程和数学等AI领域的内容学习，我们不是内容的生产者，我们向优秀的资料和优秀的学习者致敬。

[我们是谁](https://mp.weixin.qq.com/s?__biz=MzIyNjM2MzQyNg==&mid=2247483866&idx=1&sn=b2e1f343e85746ca2b0f7c7d22dc9cb1&chksm=e870d097df0759813de276464ccaec751114050f6d0dd3b505232238209ee9d97bd3eec7379d&mpshare=1&scene=1&srcid=0620KwwFDmeGtJP8dE0j836n&pass_ticket=5ZrbHq5i4kO7YEZ9KGzqnSQzpQBj9bRD2kQTYxY3wO7%2BMw3iJffHrvXBrJcrCwSu#rd)

**Comment by xiaorancs** [comment]
没有及时回复，实在不好意思，你可以放到博客上，但请注明转载出处。Datawhale是一个非盈利的 开源学习组织，致力于构建一个纯粹的学习圈子，帮助学习者更好地成长。我们专注于机器学习，深度学习，编程和数学等AI领域的内容学习，我们不是内容的生产者，我们向优秀的资料和优秀的学习者致敬。

[Datawhale](https://mp.weixin.qq.com/s?__biz=MzIyNjM2MzQyNg==&mid=2247483866&idx=1&sn=b2e1f343e85746ca2b0f7c7d22dc9cb1&chksm=e870d097df0759813de276464ccaec751114050f6d0dd3b505232238209ee9d97bd3eec7379d&mpshare=1&scene=1&srcid=0620KwwFDmeGtJP8dE0j836n&pass_ticket=5ZrbHq5i4kO7YEZ9KGzqnSQzpQBj9bRD2kQTYxY3wO7%2BMw3iJffHrvXBrJcrCwSu#rd)

**Comment by Majingmin** [comment]
抱歉，这么久才回复您。因为会在Datawhale官方CSDN账号上将小面经的每部分拿出来作为详细解读，所以暂不方便。可以关注我们CSDN号：https://me.csdn.net/datawhale查看内容，注明转载出处。如有其他问题，可以加微信：Datawhale2019详细咨询。
